server:
  port: 8080

spring:
    datasource:
      url: jdbc:mysql://45.77.199.105:3306/ele?useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=convertToNull
      username: root
      password:
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      tomcat:
        initial-size: 5
        minIdle: 5
        maxActive: 20
        maxWait: 60000


